name: tests-cygwin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: windows-latest
    env:
      FORCE_COLOR: true
    strategy:
      fail-fast: false
      matrix:
        python-minor:
          - '9'

    steps:
      - name: Tell git to use proper newlines
        run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cygwin
        uses: cygwin/cygwin-install-action@v2
        with:
          packages: >-
            python3${{ matrix.python-minor }}
            python3${{ matrix.python-minor }}-pip
            cmake make ninja gcc-core gcc-g++ git

      - name: Install nox
        shell: bash.exe -eo pipefail -o igncr "{0}"
        env:
          PATH: "/bin:/usr/bin:/usr/local/bin:/usr/lib/lapack"
          TMP: "/tmp"
          TEMP: "/tmp"
        run: |
            /usr/bin/python -m pip install nox
            nox --version

      - name: Run tests
        shell: bash.exe -eo pipefail -o igncr "{0}"
        env:
          PATH: "/bin:/usr/bin:/usr/local/bin:/usr/lib/lapack"
          CHERE_INVOKING: 1
          TMP: "/tmp"
          TEMP: "/tmp"
        run: |
          nox -s test-3.${{ matrix.python-minor }}

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        env:
          PYTHON: cygwin-3.${{ matrix.python-minor }}
        with:
          flags: tests
          env_vars: PYTHON
          name: cygwin-3.${{ matrix.python-minor }}
