name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ${{ matrix.os }}-latest
    env:
      FORCE_COLOR: true
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        python:
          - 'pypy-3.8'
          - 'pypy-3.9'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up target Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install
        run: python -m pip --disable-pip-version-check install .[test]

      - name: Run tests
        run: >-
          python -m pytest --showlocals -vv --cov
          --cov-config setup.cfg
          --cov-report=xml:coverage-${{ matrix.python }}.xml

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        env:
          PYTHON: ${{ matrix.python }}
        with:
          flags: tests
          env_vars: PYTHON
          name: ${{ matrix.python }}

  pyston:
    runs-on: ubuntu-20.04
    env:
      FORCE_COLOR: true
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.8'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pyston
        run: |
          wget https://github.com/pyston/pyston/releases/download/pyston_2.3.5/pyston_2.3.5_20.04_amd64.deb
          sudo apt install $(pwd)/pyston_2.3.5_20.04_amd64.deb

      - name: Install
        run: pyston -m pip --disable-pip-version-check install .[test]

      - name: Run tests
        run: >-
          pyston -m pytest --showlocals -vv --cov
          --cov-config setup.cfg
          --cov-report=xml:coverage-pyston.xml

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        env:
          PYTHON: pyston
        with:
          flags: tests
          env_vars: PYTHON
          name: pyston

  homebrew:
    runs-on: macos-latest
    env:
      FORCE_COLOR: true
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install homebrew Python
        run: |
          brew reinstall python@${{ matrix.python }} || true
          brew link --overwrite python@${{ matrix.python }}
          echo /usr/local/opt/python@${{ matrix.python }}/libexec/bin/ >> $GITHUB_PATH

      - run: |
          echo $PATH
          command -v python
          python --version

      - name: Install
        run: python -m pip --disable-pip-version-check install .[test]

      - name: Run tests
        run: >-
          python -m pytest --showlocals -vv --cov
          --cov-config setup.cfg
          --cov-report=xml:coverage-homebrew-${{ matrix.python }}.xml

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        env:
          PYTHON: homebrew-${{ matrix.python }}
        with:
          flags: tests
          env_vars: PYTHON
          name: homebrew-${{ matrix.python }}
